# SITE CONFIGURATION
title: Hymane's Blog # your site title
author: Hymane # You :P
description: > # Meta description of Homepage
  Hymane's blog, an Android developer. Enjoying design、backend progroming、Server and so on.
keywords: Android, Java, Design, itscoder, hymane
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hymane.itscoder.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: hymane
  links:
    - https://twitter.com/hymanmee
    - https://www.facebook.com/hymanme
    - https://www.linkedin.com/in/hymanme
    - https://plus.google.com/+hymanmee
    - https://github.com/hymanme
    - https://keybase.io/hymanme

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'Links', link: '/links'}
  - {name: 'About', link: '/about'}
  - {name: 'Résumé', link: '/assets/Résumé.pdf'}

tagline: >
  Always listen to your heart because even though it's on your left side, it's always right.❤

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: hymanmee@gmail.com # email for form submission

twitter_username: hymanmee # replace with your_twitter_username or comment to remove link from footer
github_username:  hymanme # replace with your_github_username or comment to remove link from footer
instagram_username: hymanme # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: hymane # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
